use default token location

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -25,16 +25,16 @@ if [ -z "$BUILD_IMAGE" ]; then
     exit 3
 fi
 
-if [ ! -f "/sa-secret-volume/token" ]; then
-    (>&2 echo "ERROR No service account token found at /sa-secret-volume/token. Exiting")
+if [ ! -f "/var/run/secrets/kubernetes.io/serviceaccount/token" ]; then
+    (>&2 echo "ERROR No service account token found at /var/run/secrets/kubernetes.io/serviceaccount/token. Exiting")
     exit 4
 fi
 
 # do login
 oc login ${INSECURE_SKIP_TLS_VERIFY} \
     ${OPENSHIFT_SERVER} \
-    --certificate-authority='/sa-secret-volume/ca.crt' \
-    --token="$(< /sa-secret-volume/token)"
+    --certificate-authority='/var/run/secrets/kubernetes.io/serviceaccount/ca.crt' \
+    --token="$(< /var/run/secrets/kubernetes.io/serviceaccount/token)"
 
 if [[ "$?" != "0" ]]; then
     (>&2 echo "ERROR Could not oc login using token at sa-secret-volume/token. Exiting")
