fix path

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -25,8 +25,8 @@ if [ -z "$BUILD_IMAGE" ]; then
     exit 3
 fi
 
-if [ ! -f "sa-secret-volume/token" ]; then
-    (>&2 echo "ERROR No service account token found at sa-secret-volume/token. Exiting")
+if [ ! -f "/sa-secret-volume/token" ]; then
+    (>&2 echo "ERROR No service account token found at /sa-secret-volume/token. Exiting")
     exit 4
 fi
 
